# variables: https://git.drupalcode.org/project/gitlab_templates/-/blob/1.0.x/includes/include.drupalci.variables.yml
include:
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

variables:
  #  Disable default phpunit job in favor of the d9/10 variants below.
  SKIP_PHPUNIT: 1
  _PHPUNIT_EXTRA: --verbose
  # Convenient, and we have no secrets.
  _SHOW_ENVIRONMENT_VARIABLES: 1

# Run two variations of composer job.
composer:
  parallel:
    matrix:
      - _TARGET_PHP: [ "7.4" ]
        _TARGET_CORE: [ "9.5.11" ]
      - _TARGET_PHP: [ "8.1" ]
        _TARGET_CORE: [ "$CORE_STABLE" ]

#
# The 4 validation jobs below are explicit which composer built codebase they wish to use https://docs.gitlab.com/ee/ci/jobs/job_control.html#fetch-artifacts-from-a-parallelmatrix-job
#

phpcs:
  # Set allow_failure to false so that the test fails for coding standards faults.
  allow_failure: true
  needs:
    - "composer: [8.1, $CORE_STABLE]"

composer-lint:
  needs:
    - "composer: [8.1, $CORE_STABLE]"

eslint:
  needs:
    - "composer: [8.1, $CORE_STABLE]"

stylelint:
  needs:
    - "composer: [8.1, $CORE_STABLE]"

.phpunit-local:
  variables:
    SKIP_PHPUNIT: 0

phpunit-d9:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "7.4"
            _TARGET_CORE: "9.5.11"
  variables:
    _TARGET_PHP: "7.4"
  extends:
    - .phpunit-base
    - .phpunit-local

phpunit-d10:
  needs:
    - job: composer
      parallel:
        matrix:
          - _TARGET_PHP: "8.1"
            _TARGET_CORE: $CORE_STABLE
  variables:
    _TARGET_PHP: "8.1"
  extends:
    - .phpunit-base
    - .phpunit-local
