field.widget.settings.readonly_field_widget:
  type: mapping
  label: 'Readonly Field Widget display format settings'
  mapping:
    label:
      type: string
      label: 'Label'
    formatter_type:
      type: string
      label: 'Format'
    formatter_settings:
      type: sequence
      label: 'Formatter Settings'
      sequence:
        type: field.formatter.settings.[%key]
    show_description:
      type: boolean
      label: 'Show Description'
